#!/usr/bin/env sh
export ANSIBLE_COLLECTIONS_PATH=~/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections
export ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:collection/roles
ansible-lint
