# -*- mode: ruby -*-
# vi: set ft=ruby :

c2n1Vdi = '../../tmp/c2-n1.vdi'
c2n2Vdi = '../../tmp/c2-n2.vdi'

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.box = "debian/stretch64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "1"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
  config.vm.define "c2-n1" do |machine|
    machine.vm.hostname = "c2-n1"
    machine.vm.network "private_network", ip: "192.168.11.21"
    machine.vm.provider "virtualbox" do |vbm|
      unless File.exist?(c2n1Vdi)
        vbm.customize ['createhd', '--filename', c2n1Vdi, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vbm.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', c2n1Vdi]
    end
  end
  config.vm.define "c2-n2" do |machine|
    machine.vm.hostname = "c2-n2"
    machine.vm.network "private_network", ip: "192.168.11.22"
    machine.vm.provider "virtualbox" do |vbm|
      unless File.exist?(c2n2Vdi)
        vbm.customize ['createhd', '--filename', c2n2Vdi, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vbm.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', c2n2Vdi]
    end
  end
end
