# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # common
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
  end
  # c2-n1
  config.vm.define "c2-n1" do |machine|
    machine.vm.box = "generic/debian10"
    machine.vm.hostname = "c2-n1"
    machine.vm.network :private_network, :ip => "192.168.11.21", :libvirt__domain_name => "homecloud.local"
    machine.vm.provider "libvirt" do |libvirt|
      libvirt.storage :file, :size => '5G'
    end
    vdi = '../../tmp/c2-n1.vdi'
    machine.vm.provider "virtualbox" do |vb|
      unless File.exist?(vdi)
        vb.customize ['createhd', '--filename', vdi, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', vdi]
    end
    machine.vm.provision "shell", inline: <<-SHELL
      apt-get update
      lsblk
      mkfs.ext4 -F /dev/vdb || mkfs.ext4 /dev/sdb
    SHELL
  end
  # c2-n2
  config.vm.define "c2-n2" do |machine|
    machine.vm.box = "generic/debian9"
    machine.vm.hostname = "c2-n2"
    machine.vm.network :private_network, :ip => "192.168.11.22", :libvirt__domain_name => "homecloud.local"
    machine.vm.provider "libvirt" do |libvirt|
      libvirt.storage :file, :size => '5G'
    end
    vdi = '../../tmp/c2-n2.vdi'
    machine.vm.provider "virtualbox" do |vb|
      unless File.exist?(vdi)
        vb.customize ['createhd', '--filename', vdi, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', vdi]
    end
    machine.vm.provision "shell", inline: <<-SHELL
      apt-get update
      lsblk
    SHELL
  end

end
