# -*- mode: ruby -*-
# vi: set ft=ruby :

d1n1Vdi = '../../tmp/d1-n1.vdi'

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1048"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    mkfs.ext4 /dev/sdb
  SHELL
  config.vm.define "d1-n1" do |machine|
    machine.vm.hostname = "d1-n1"
    machine.vm.network "private_network", ip: "192.168.13.11"
    machine.vm.provider "virtualbox" do |vbm|
      unless File.exist?(d1n1Vdi)
        vbm.customize ['createhd', '--filename', d1n1Vdi, '--variant', 'Fixed', '--size', 5 * 1024]
      end
      vbm.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', d1n1Vdi]
    end
  end
end
