# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
  config.vm.define "c1-n1" do |machine|
    machine.vm.hostname = "c1-n1"
    machine.vm.network "private_network", ip: "192.168.11.11"
  end
end
