@startwbs components_overview_hierarchy
skinparam monochrome true
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.gdiag/plantuml-libs/dist"
!include $LIB_BASE_LOCATION/bootstrap.puml
include('homecloud/Brand/Traefik')
include('homecloud/Brand/Nextcloud')
include('homecloud/Brand/Syncthing')
include('homecloud/Brand/Calibreweb')
include('homecloud/Brand/Keepalived')
include('homecloud/Brand/Samba')
include('simpleicons-4/K/Kubernetes')
include('fontawesome-5.15/Solid/Home')
include('material-4.0/Device/Widgets')
* <$HomeMd> homecloud
** <$KubernetesMd> Kubernetes
*** <$TraefikMd> Traefik
*** <$WidgetsMd> Longhorn
*** <$KubernetesMd> Dashboard
*** <$NextcloudMd> Nextcloud
*** <$SambaMd> dnas-share (Samba, NFS)
*** <$CalibrewebMd> calibre-web
** <$KeepalivedMd> Keepalived
** <$SyncthingMd> Syncthing
@endwbs
