@startuml user_services_layout
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.gdiag/plantuml-libs"
!include $LIB_BASE_LOCATION/bootstrap.puml

skinparam RectangleShadowing false
skinparam RectangleBorderStyle dotted

include('homecloud-1/bootstrap')
include('homecloud-1/Network/Internet')
include('homecloud-1/Network/LocalNetwork')
include('homecloud-1/Network/Router')
include('homecloud-1/Brand/Nextcloud')
include('homecloud-1/Brand/Syncthing')
include('homecloud-1/Brand/Samba')
include('homecloud-1/Brand/Calibreweb')
include('homecloud-1/Brand/Dnas')

Internet('internet', 'Internet')
LocalNetworkGroup('home', 'home network') {
  Router('router', 'router')
  DnasGroup('dans') {
    Syncthing('syncthing', 'Syncthing')
    Samba('samba', 'Samba')
  }
  Nextcloud('nextcloud', 'Nextcloud')
  Calibreweb('calibreweb', 'calibre-web')
}
internet - router
router -- syncthing
router -- samba
router -- nextcloud
router -- calibreweb
@enduml

@startuml user_services_dnas
!global $INCLUSION_MODE="local"
!global $LIB_BASE_LOCATION="../.gdiag/plantuml-libs"
!include $LIB_BASE_LOCATION/bootstrap.puml

skinparam RectangleShadowing false
skinparam RectangleBorderStyle dotted

include('homecloud-1/bootstrap')

include('homecloud-1/Hardware/Board')
include('homecloud-1/Hardware/Smartphone')
include('homecloud-1/Hardware/Laptop')
include('homecloud-1/Hardware/Hdd')
include('homecloud-1/Network/Internet')
include('homecloud-1/Network/LocalNetwork')
include('homecloud-1/Network/Router')

include('homecloud-1/Brand/Nextcloud')
include('homecloud-1/Brand/Syncthing')
include('homecloud-1/Brand/Samba')
include('homecloud-1/Brand/Calibreweb')
include('homecloud-1/Brand/Dnas')

Internet('internet', 'Internet')
SmartphoneGroup('smartphone', 'Smartphone') {
  Syncthing('syncthing_phone', 'Syncthing')
}
LocalNetworkGroup('home', 'home network') {
  Router('router', 'router')
  Laptop('laptop', 'Laptop')
  DnasGroup('dnas', 'DNAS') {
    Syncthing('syncthing', 'Syncthing')
    Samba('samba', 'Samba')
    Hdd('ssd', 'SSD Disk')
  }
}
internet -left- router
internet -- syncthing_phone
router -- syncthing
router -- samba
router -- laptop
laptop .right.> samba : Relationship('read/write')
syncthing_phone <.left.> syncthing : Relationship('replication')
syncthing --> ssd
samba --> ssd
@enduml
